// import { Inter } from "next/font/google";
import Link from "next/link";
import "../globals.css";
import { Button } from "@/components/ui/button";
import { FileIcon, Star, Loader2, } from "lucide-react";
import { SideNav } from "./_components/sideNav";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({children,}: Readonly<{children: React.ReactNode}>){
  
  return (
    <main className="m-4 pt-12">
    <div className="flex gap-4">
      <SideNav/>
      <div className="w-full">{children}</div>
      </div>
  </main>
  );
}
